apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
  namespace: lesson-1
  labels:
    app: app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
        - name: app-python
          image: xiozip/app-python:v1
          ports:
            - containerPort: 8000
