apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-vuejs
  namespace: lesson-1
  labels:
    app: app-vuejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-vuejs
  template:
    metadata:
      labels:
        app: app-vuejs
    spec:
      containers:
        - name: app-vuejs
          image: xiozip/app-vuejs:v3
          ports:
            - containerPort: 8080
